name: workflow2
on: push
jobs: 
  get-code:
    runs-on: ubuntu-latest
    steps:
    - name: Get Code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: npm ci
  job-lint:
    runs-on: ubuntu-latest
    steps:
      - name: node lint
        run: npm run lint
  job-test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: npm  test
  job-build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: npm run build